import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AuthWrapper from "@/components/AuthWrapper";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Head from "next/head";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Deliziare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="apple-touch-icon" href="/icons/16.png" />
        <meta name="msapplication-TileImage" content="/windows/LargeTile.scale-100.png" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <GoogleOAuthProvider clientId="274859593300-jfocmqdd23trfhhlkrh45v2hmcii8fi3.apps.googleusercontent.com">
        <Providers>
          <AuthWrapper >
            {children}
          </AuthWrapper>
       
        </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
