import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import AuthWrapper from "@/components/AuthWrapper";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AuthInitializer from "@/lib/authInitializer";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Deliziare",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <GoogleOAuthProvider clientId="274859593300-jfocmqdd23trfhhlkrh45v2hmcii8fi3.apps.googleusercontent.com">
        <Providers>
          
            
            {children}
            
       
        </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
